src/Entity/ShoppingList.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShoppingListRepository")
 */
class ShoppingList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="shoppingLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expectedDeliveryStart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expectedDeliveryEnd;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $recipe;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $hasClientAccepted;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $hasDeliveryAccepted;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deliveredAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Delivery", inversedBy="ShoppingLists")
     */
    private $delivery;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductsList", mappedBy="shoppingList", orphanRemoval=true, cascade={"persist"})
     */
    private $products;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    private $totalPrice;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function isDelivered(): bool
    {
        return (!empty($this->deliveredAt) && $this->hasClientAccepted && $this->hasDeliveryAccepted);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getExpectedDeliveryStart(): ?\DateTimeInterface
    {
        return $this->expectedDeliveryStart;
    }

    public function setExpectedDeliveryStart(\DateTimeInterface $expectedDeliveryStart): self
    {
        $this->expectedDeliveryStart = $expectedDeliveryStart;

        return $this;
    }

    public function getExpectedDeliveryEnd(): ?\DateTimeInterface
    {
        return $this->expectedDeliveryEnd;
    }

    public function setExpectedDeliveryEnd(\DateTimeInterface $expectedDeliveryEnd): self
    {
        $this->expectedDeliveryEnd = $expectedDeliveryEnd;

        return $this;
    }

    public function getRecipe(): ?string
    {
        return $this->recipe;
    }

    public function setRecipe(?string $recipe): self
    {
        $this->recipe = $recipe;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getHasClientAccepted(): ?bool
    {
        return $this->hasClientAccepted;
    }

    public function setHasClientAccepted(?bool $hasClientAccepted): self
    {
        $this->hasClientAccepted = $hasClientAccepted;

        return $this;
    }

    public function getHasDeliveryAccepted(): ?bool
    {
        return $this->hasDeliveryAccepted;
    }

    public function setHasDeliveryAccepted(?bool $hasDeliveryAccepted): self
    {
        $this->hasDeliveryAccepted = $hasDeliveryAccepted;

        return $this;
    }

    public function getDeliveredAt(): ?\DateTimeInterface
    {
        return $this->deliveredAt;
    }

    public function setDeliveredAt(?\DateTimeInterface $deliveredAt): self
    {
        $this->deliveredAt = $deliveredAt;

        return $this;
    }

    public function getDelivery(): ?Delivery
    {
        return $this->delivery;
    }

    public function setDelivery(?Delivery $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection|ProductsList[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(ProductsList $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setShoppingList($this);
        }

        return $this;
    }

    public function removeProduct(ProductsList $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getShoppingList() === $this) {
                $product->setShoppingList(null);
            }
        }

        return $this;
    }

    public function getTotalPrice(): ?string
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(string $totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Address", mappedBy="user", orphanRemoval=true)
     */
    private $addresses;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phoneNumber;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Delivery", mappedBy="user", orphanRemoval=true)
     */
    private $deliveries;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ShoppingList", mappedBy="user", orphanRemoval=true)
     */
    private $shoppingLists;

    public function __construct()
    {
        $this->baskets = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->deliveries = new ArrayCollection();
        $this->shoppingLists = new ArrayCollection();
    }

    public function getFullname(): string
    {
        return ucfirst($this->firstname). ' ' .ucfirst($this->lastname);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setUser($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->contains($address)) {
            $this->addresses->removeElement($address);
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * @return Collection|Delivery[]
     */
    public function getDeliveries(): Collection
    {
        return $this->deliveries;
    }

    public function addDelivery(Delivery $delivery): self
    {
        if (!$this->deliveries->contains($delivery)) {
            $this->deliveries[] = $delivery;
            $delivery->setUser($this);
        }

        return $this;
    }

    public function removeDelivery(Delivery $delivery): self
    {
        if ($this->deliveries->contains($delivery)) {
            $this->deliveries->removeElement($delivery);
            // set the owning side to null (unless already changed)
            if ($delivery->getUser() === $this) {
                $delivery->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ShoppingList[]
     */
    public function getShoppingLists(): Collection
    {
        return $this->shoppingLists;
    }

    public function addShoppingList(ShoppingList $shoppingList): self
    {
        if (!$this->shoppingLists->contains($shoppingList)) {
            $this->shoppingLists[] = $shoppingList;
            $shoppingList->setUser($this);
        }

        return $this;
    }

    public function removeShoppingList(ShoppingList $shoppingList): self
    {
        if ($this->shoppingLists->contains($shoppingList)) {
            $this->shoppingLists->removeElement($shoppingList);
            // set the owning side to null (unless already changed)
            if ($shoppingList->getUser() === $this) {
                $shoppingList->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/ShoppingListType.php
<?php

namespace App\Form;

use App\Entity\ShoppingList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShoppingListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('expectedDeliveryStart', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datepicker'
                ],
                'required' => true
            ])
            ->add('expectedDeliveryEnd', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datepicker'
                ],
                'required' => true
            ])
            ->add('products', CollectionType::class, [
                'entry_type' => ProductsListType::class,
                'allow_add' => true,
                'prototype' => true,
                'required' => true
            ])
            ->add('confirmer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ShoppingList::class,
        ]);
    }
}

src/Controller/ShoppingListController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\ShoppingList;
use App\Form\ShoppingListType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ShoppingListController extends AbstractController
{
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/shopping/list/{id}", name="shopping_details")
     */
    public function details(int $id)
    {
        $list = $this->em->getRepository(ShoppingList::class)->findOneBy(['id' => $id, 'user' => $this->getUser()]);
        if (empty($list)) return $this->redirectToRoute('index');

        return $this->render('shopping_list/details.html.twig', [
            'shopping_list' => $list
        ]);
    }

    /**
     * @Route("/shopping", name="shopping_list")
     */
    public function index(Request $request)
    {
        $products = $this->em->getRepository(Product::class)->findAll();

        $form = $this->createForm(ShoppingListType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $shoppingList = $form->getData();
            $shoppingList
                ->setUser($this->getUser())
                ->setCreatedAt(new \DateTime('now'));

            $total = 0;
            foreach ($shoppingList->getProducts() as $product)
            {
                $total += $product->getProduct()->getPrice() * $product->getQuantity();
            }
            $shoppingList->setTotalPrice($total);            
            
            $this->em->persist($shoppingList);
            $this->em->flush();

            return $this->redirectToRoute('index');
        }

        return $this->render('shopping_list/index.html.twig', [
            'products' => $products,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/shopping/validate/{id}", name="shopping_validate")
     */
    public function validate(int $id)
    {
        $list = $this->em->getRepository(ShoppingList::class)->findOneBy(['id' => $id]);
        if (empty($list)) return $this->redirectToRoute('index');

        if ($list->getUser() == $this->getUser())
        {
            $list->setHasClientAccepted(true);
            $this->em->persist($list);
            $this->em->flush();

            return $this->redirectToRoute('shopping_details', ['id' => $id]);
        } 
        else if ($list->getDelivery()->getUser() == $this->getUser())
        {
            $list
                ->setDeliveredAt(new \DateTime('now'))
                ->setHasDeliveryAccepted(true);
            $this->em->persist($list);
            $this->em->flush();

            return $this->redirectToRoute('delivery_details', ['id' => $list->getDelivery()->getId()]);
        }
        
        return $this->redirectToRoute('index');
    }
}

templates/shopping_list/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="row d-flex justify-content-center">
    <div class="col-4">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <p>Commande du {{ shopping_list.createdAt|date('d/m/Y') }}</p>
                {% if shopping_list.delivery is not null %}<p>Livreur : {{ shopping_list.delivery.user.fullname }}</p>{% endif %}
            </div>
            <div class="card-body">
                {% for product in shopping_list.products %}
                    <div class="card-text d-flex justify-content-between">
                        <p><span class="mr-2">x{{ product.quantity }}</span> {{ product.product.name }}</p>
                        <p>{{ product.product.price }} €</p>
                    </div>
                {% endfor %}
            </div>
            <div class="d-flex justify-content-between card-footer {{ shopping_list.isDelivered ? 'bg-success' : 'bg-warning' }}">
                {% if shopping_list.isDelivered %}
                    <p>Livraison reçu le {{ shopping_list.deliveredAt|date('d/m/Y') }}</p>
                {% elseif shopping_list.hasClientAccepted %}
                    <p>En attente de confirmation du livreur...</p>
                {% elseif shopping_list.delivery.id is not defined %}
                    <p>En attente de la prise en charge de votre commande...</p>
                {% else %}
                    <a href="{{ path('shopping_validate', {id: shopping_list.id}) }}" class="btn btn-success">Confirmer la réception</a>
                {% endif %}
                {% if shopping_list.totalPrice is not null %}<p>Total : {{ shopping_list.totalPrice }} €</p>{% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/shopping_list/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="row align-items-start">
    <div class="offset-1 col-6 table-responsive">
        <table class="table" id="product-list" width="100%">
            <thead>
                <tr>
                    <th scope="col">Produit</th>
                    <th scope="col">Description</th>
                    <th scope="col" class="text-right">Prix</th>
                    <th scope="col" width="10%"></th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr product-data-id="{{ product.id }}">
                        <td>{{ product.name }}</td>
                        <td>{{ product.description }}</td>
                        <td class="text-right">{{ (product.price)|number_format(2, ',', ' ') }} €</td>
                        <td class="text-center"><a href="#" class="add-product"><i class="fa fa-shopping-basket"></i></a></td>
                    </tr>
                {% endfor %}
            </tbody> 
        </table>
    </div>
    <div class="offset-1 col-4 sticky-top p-5">
        {{ form_start(form, {attr: {class: 'card' }} )}}
            <div class="card-header">
                Nouvelle liste de courses
            </div>
            {% set data_prototype %}
                <div class="card-text d-flex justify-content-between basket-product">
                    <p>__PRODUCT__</p>
                    <div class="row form-group d-flex justify-content-end">
                        <div hidden>
                            {{ form_widget(form.products.vars.prototype.product) }}
                        </div>
                        {{ form_widget(form.products.vars.prototype.quantity, {attr: {class: 'col-4 mr-2'}}) }}
                        <span class="d-flex align-items-center"><a href="#" class="remove-product"><i class="fa fa-trash"></i></a></span>
                    </div>
                </div>
            {% endset %}
            <div class="card-body" id="basket" data-prototype="{{ data_prototype|e }}" data-counter="{{ form.products|length }}">
                <div class="card-title">
                    Livraison entre le {{ form_widget(form.expectedDeliveryStart) }} et le {{ form_widget(form.expectedDeliveryEnd) }}
                </div>
                {% for product in form.products %}
                <div class="card-text d-flex justify-content-between basket-product">
                    <p>{{ product.product.vars.data.name }}</p>
                    <div class="row form-group d-flex justify-content-end">
                        <div hidden>
                            {{ form_widget(product.product) }}
                        </div>
                        {{ form_widget(product.quantity, {attr: {class: 'col-4 mr-2'}}) }}
                        <span class="d-flex align-items-center"><a href="#" class="remove-product"><i class="fa fa-trash"></i></a></span>
                    </div>
                </div>
                {% endfor %}
                <div class="d-flex justify-content-around row">
                    <div class="col-6">
                        <a href="{{ path('index') }}" class="btn btn-danger btn-block">Annuler</a>
                    </div>
                    <div class="col-6">
                        {{ form_widget(form.confirmer, {attr: {class: 'btn btn-success btn-block'}} ) }}
                    </div>
                </div>
            </div>
            {{ form_widget(form._token) }}
        {{ form_end(form, {render_rest: false}) }}
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            var table = $("#product-list").DataTable({
                'pagingType': 'full',
                'responsive': true,
                'autoWidth': true,
                'pageLength': 20,
                'lengthChange': false
            })

            var form = $("#basket")
            var basket = {};
            $('#basket > basket-product').each(function(elem){
                let input = $($(elem).find('input')[0])
                basket[input.val()] = $(elem)
            })

            $("#product-list").on('click', '.add-product', function(event) {
                event.preventDefault()
                event.stopPropagation()

                let t = $(event.target)
                let row = $(t.closest('tr'))
                let cols = row.find('td')
                let productName = $(cols[0]).text()
                let productId = parseInt(row.attr('product-data-id'))

                if (basket[productId] !== undefined) {
                    let input = $(basket[productId].find('input')[0])
                    input.val(parseInt(input.val()) + 1)
                    return
                }

                let count = parseInt(form.attr('data-counter')) + 1
                form.attr('data-counter', count)
                let prototype = form.attr('data-prototype')
                prototype = prototype.replace(/__name__/g, count)
                prototype = prototype.replace(/__PRODUCT__/g, productName)
                prototype = $(prototype)
                let inputs = prototype.find('input')
                $(prototype.find('select')).find('option').each(function(i, elem){
                    if ($(elem).attr('value') == productId) $(elem).attr('selected', 'selected')
                })
                $(inputs[0]).val(1)
                $(form.find('.card-title').after(prototype))
                basket[productId] = prototype
                console.log(basket)
            })

            $('#basket').on('click', '.remove-product', function(event){
                event.preventDefault()
                event.stopPropagation()
                
                let t = $(event.target)
                let row = $(t.closest('.basket-product'))
                row.find('select option').each(function(i, elem){
                    if ($(elem).attr('selected') === 'selected') delete basket[$(elem).attr('value')]
                })
                row.remove()
            })
        })
    </script>
{% endblock %}